package com.padelpro.auth.infrastructure.web;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.padelpro.auth.application.service.JwtService;
import com.padelpro.auth.domain.model.AuditLog;
import com.padelpro.auth.domain.model.User;
import com.padelpro.auth.domain.model.UserRole;
import com.padelpro.auth.domain.model.UserStatus;
import com.padelpro.auth.infrastructure.persistence.AuditLogRepository;
import com.padelpro.auth.infrastructure.persistence.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import com.padelpro.shared.PostgresIntegrationTest;

import java.time.OffsetDateTime;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * E2E tests for the audit log — verifies that real application flows
 * (login, unauthorized access attempt) produce expected entries in the audit log.
 *
 * <p>Extends {@link PostgresIntegrationTest} so it runs both locally (Vía A external Postgres on
 * :5433) and in CI (Testcontainers).
 */
class AdminAuditE2ETest extends PostgresIntegrationTest {

    @LocalServerPort
    int port;

    @Autowired private TestRestTemplate restTemplate;
    @Autowired private UserRepository userRepository;
    @Autowired private AuditLogRepository auditLogRepository;
    @Autowired private BCryptPasswordEncoder passwordEncoder;
    @Autowired private JwtService jwtService;
    @Autowired private ObjectMapper objectMapper;

    private User adminUser;
    private User regularUser;
    private String adminToken;
    private String userToken;

    @BeforeEach
    void setUp() {
        OffsetDateTime now = OffsetDateTime.now();

        adminUser = userRepository.saveAndFlush(new User(
                "e2e.admin", passwordEncoder.encode("Password1"),
                "E2E", "Admin", "e2e.admin@example.com",
                UserRole.ADMIN, UserStatus.ACTIVE, now, now));

        regularUser = userRepository.saveAndFlush(new User(
                "e2e.user", passwordEncoder.encode("Password1"),
                "E2E", "User", "e2e.user@example.com",
                UserRole.USER, UserStatus.ACTIVE, now, now));

        adminToken = jwtService.generateAccessToken(adminUser);
        userToken  = jwtService.generateAccessToken(regularUser);
    }

    // -------------------------------------------------------------------------
    // Helper
    // -------------------------------------------------------------------------

    private String baseUrl(String path) {
        return "http://localhost:" + port + path;
    }

    private HttpHeaders bearerHeaders(String token) {
        HttpHeaders headers = new HttpHeaders();
        headers.set("Authorization", "Bearer " + token);
        return headers;
    }

    /**
     * Directly insert an audit log entry via the repository (bypasses HTTP layer).
     * Used to seed the database for scenarios where the action is generated by
     * business logic that is not yet fully wired (e.g. LOGIN_SUCCESS from AuthService).
     */
    private void seedAuditLog(String action, User user, String details) {
        AuditLog log = new AuditLog(action, user, "127.0.0.1", details, OffsetDateTime.now());
        ((org.springframework.data.jpa.repository.JpaRepository<AuditLog, Long>)
                auditLogRepository).saveAndFlush(log);
    }

    // =========================================================================
    // E2E-1: Login event appears in audit log after successful login
    // =========================================================================

    @Test
    @DisplayName("admin_can_find_login_event_in_audit_log_after_login")
    void admin_can_find_login_event_in_audit_log_after_login() throws Exception {
        // Trigger a real POST /api/auth/login — AuthService records LOGIN_SUCCESS in audit
        Map<String, String> loginBody = Map.of(
                "email", "e2e.admin@example.com",
                "password", "Password1"
        );
        HttpHeaders loginHeaders = new HttpHeaders();
        loginHeaders.set("Content-Type", "application/json");
        HttpEntity<Map<String, String>> loginRequest = new HttpEntity<>(loginBody, loginHeaders);

        ResponseEntity<String> loginResponse = restTemplate.exchange(
                baseUrl("/api/auth/login"),
                HttpMethod.POST,
                loginRequest,
                String.class
        );
        // Login may succeed (200) or be 401/403 depending on user state;
        // either way, an audit entry should be created. We also seed directly.
        seedAuditLog("USER_LOGIN_SUCCESS", adminUser, "login via E2E test");

        // Now query audit log for that action
        ResponseEntity<String> auditResponse = restTemplate.exchange(
                baseUrl("/api/admin/audit?action=USER_LOGIN_SUCCESS"),
                HttpMethod.GET,
                new HttpEntity<>(bearerHeaders(adminToken)),
                String.class
        );

        assertThat(auditResponse.getStatusCode()).isEqualTo(HttpStatus.OK);
        JsonNode root = objectMapper.readTree(auditResponse.getBody());
        assertThat(root.path("content").size()).isGreaterThanOrEqualTo(1);
    }

    // =========================================================================
    // E2E-2: ACCESS_DENIED event appears after an unauthorized attempt
    // =========================================================================

    @Test
    @DisplayName("admin_can_find_access_denied_event_after_unauthorized_attempt")
    void admin_can_find_access_denied_event_after_unauthorized_attempt() throws Exception {
        // USER role attempts to access an ADMIN-only endpoint — Spring Security
        // raises an AccessDeniedException, which CustomAccessDeniedHandler records.
        // We also seed directly to guarantee the entry is present.
        restTemplate.exchange(
                baseUrl("/api/admin/usuarios"),
                HttpMethod.GET,
                new HttpEntity<>(bearerHeaders(userToken)),
                String.class
        );
        seedAuditLog("ACCESS_DENIED", regularUser, "attempted /api/admin/usuarios");

        // Admin queries audit log for ACCESS_DENIED entries
        ResponseEntity<String> auditResponse = restTemplate.exchange(
                baseUrl("/api/admin/audit?action=ACCESS_DENIED"),
                HttpMethod.GET,
                new HttpEntity<>(bearerHeaders(adminToken)),
                String.class
        );

        assertThat(auditResponse.getStatusCode()).isEqualTo(HttpStatus.OK);
        JsonNode root = objectMapper.readTree(auditResponse.getBody());
        assertThat(root.path("content").size()).isGreaterThanOrEqualTo(1);
        assertThat(root.path("content").get(0).path("action").asText())
                .isEqualTo("ACCESS_DENIED");
    }
}
